# @baseUrl = http://localhost:3000
@password = password1234

{{baseUrl}}/api/health

### Get all books
{{baseUrl}}/api/books

### Create a book
# @no-cookie-jar
POST {{baseUrl}}/api/books
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "publishedDate": "1925-04-10"
}

### Create account
# @no-cookie-jar
# @prompt email
POST {{baseUrl}}/api/auth/sign-up/email
Content-Type: application/json

{
  "name": "john",
  "email": "{{email}}",
  "password": "{{password}}"
}

###
curl --request GET --url http://localhost:3000/api/health --header 'user-agent: vscode-restclient'